version: '3'
services:
  app:
    container_name: node-server
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/node-server
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb:/data/db

