db.user.insertMany([
    {
        "nombre":"Nombre1",
        "apellido":"Apellido1",
        "email":"email1",
        "passowrd":"pass1"
    },
    {
        "nombre":"Nombre2",
        "apellido":"Apellido2",
        "email":"email2",
        "passowrd":"pass2"
    },
    {
        "nombre":"Nombre2",
        "apellido":"Apellido2",
        "email":"email2",
        "passowrd":"pass2"
    },
    {
        "nombre":"Nombre2",
        "apellido":"Apellido2",
        "email":"email2",
        "passowrd":"pass2"
    }
])